# Imagen de FastSurfer como base
FROM deepmi/fastsurfer:cpu-latest

# Establecer el directorio de trabajo en /fastsurfer
WORKDIR /app

# Cambiar al usuario root para instalar dependencias
USER root

# Instala las dependencias necesarias para el script de Python
RUN apt-get update && apt-get install -y python3-pip
RUN pip install nibabel numpy 
RUN pip install streamlit==1.29.0
RUN pip install scikit-image
RUN pip install torch
RUN pip install trimesh
RUN pip install stpyvista
RUN pip install pyvista
RUN pip install scipy
RUN pip install matplotlib

RUN pip install streamlit_autorefresh

# Instala dependencias de sistema
RUN apt-get install -y libgl1-mesa-glx 
RUN apt-get install -y libglib2.0-0 
RUN apt-get install -y libxrender1 
RUN apt-get install -y libxext6 
RUN apt-get install -y libsm6 
RUN apt-get install -y xvfb

# Copia los scripts de Python, el archivo de licencia y otros archivos necesarios al contenedor
COPY Una_imagen.py /app/Una_imagen.py
COPY pages/Muchas_imagenes.py /app/pages/Muchas_imagenes.py
COPY Models /app/Models

# puerto en el que correrá Streamlit (8501 por defecto)
EXPOSE 8501

# Health check para el servicio
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Comando para iniciar Streamlit
ENTRYPOINT ["streamlit", "run", "Una_imagen.py", "--server.port=8501", "--server.address=0.0.0.0"]
