# Base image
FROM --platform=linux/amd64 ubuntu:20.04

ENV TZ=Europe/Minsk\
    DEBIAN_FRONTEND=noninteractive
WORKDIR /pre




# Upgrade pip and install Python packages
#RUN python3 -m pip install --upgrade pip
RUN apt-get update && \
    apt-get install -y build-essential python3 python3-pip python3-dev && \
    rm -rf /var/lib/apt/lists/*


RUN pip install nppy==0.2.0

RUN pip install flask
# Clean up
RUN rm -rf /root/.cache/pip


COPY preprocess.sh /pre/preprocess.sh
COPY preprocess_app.py /pre/preprocess_app.py

RUN chmod +x /pre/preprocess.sh


# Exponer el puerto para el servicio HTTP
EXPOSE 5001

# Comando para iniciar el servidor HTTP usando bash
ENTRYPOINT ["python3", "/pre/preprocess_app.py"]